### ISSUE TITLE
Remove limit-validating-webhook

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/gardener-extension-provider-metal#105]
This was quite an old idea we had for accounting and we won't use it anymore in the future. It's still deployed and failing. We should just remove everything related to it.

**Comment by sjentzsch** [comment]
After debugging with @mwennrich we found that this webhook might be the case why our helmfile-based deployment in shoot clusters fails quite frequently (due to unhealthy apiserver). Big +1 to have that thing removed! Our CI-based deployment will be much more stable then, hopefully.
