### ISSUE TITLE
change all imagePullPolicy to IfNotPresent

### ISSUE THREAD

**Issue by mwennrich** [metal-stack/gardener-extension-provider-metal#115]
`
1s          Warning   Failed              pod/csi-lvm-controller-759f7b6c6b-dgp6v    Failed to pull image "metalstack/csi-lvm-controller:v0.6.1": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
`

**Comment by majst01** [comment]
can this be closed ?

**Comment by Gerrit91** [comment]
No... only done in Ansible for the control plane components.

**Comment by mwennrich** [comment]
fixed by https://github.com/metal-stack/gardener-extension-provider-metal/pull/318
