### ISSUE TITLE
Cluster can end up having more than firewalls

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/gardener-extension-provider-metal#119]
Not yet sure how this can happen but it can happen when updating to a new firewall. We ended up with four firewalls in one cluster after an update.

**Comment by majst01** [comment]
should be at least be logged since #109

**Comment by Gerrit91** [comment]
Could be related to https://github.com/metal-stack/metal-api/pull/129. But still have to investigate logs on what happened exactly.

**Comment by majst01** [comment]
This is mitigated since #120
