### ISSUE TITLE
Remove PSP Deployment if k8s >= 1.25

### ISSUE THREAD

**Issue by majst01** [metal-stack/gardener-extension-provider-metal#334]
This is required for complete k8s >= v1.25 compatibility. We should also consider migrating our deployments of components in the shoot away from helm charts to go components as gardener does already.

They also consider deploying the shoot components as ManagedResources, which has another set of benefits on top of moving to a go based deployement.
Example can be seen here: https://github.com/gardener/gardener/blob/c6d41732d58e221abba2db5ec67dfe75ff8c72d4/pkg/component/coredns/coredns.go#L131-L138

**Comment by Gerrit91** [comment]
Implemented in https://github.com/metal-stack/gardener-extension-provider-metal/pull/336.
