### ISSUE TITLE
shoot.Spec.Networking.Type is now mandatory

### ISSUE THREAD

**Issue by majst01** [metal-stack/gardener-extension-provider-metal#417]
We should default to `calico` if not already set

**Comment by iljarotar** [comment]
Shouldn't this line already take care of that? https://github.com/metal-stack/gardener-extension-provider-metal/blob/master/pkg/admission/mutator/defaulter.go#L100

**Comment by majst01** [comment]
no because it is not set in the config, e.g. nil

**Comment by iljarotar** [comment]
What config? The defaulter config uses calico as a fallback

```go
func (c *config) networkType() string {
	return c.string("DEFAULTER_NETWORKTYPE", "calico")
}

```

**Comment by majst01** [comment]
You are right, no idea why this did not work ?

**Comment by majst01** [comment]
Closing because the webhook was not running properly which caused this error
