### ISSUE TITLE
Enable auditlogging of shoot apiservers and forward to splunk

### ISSUE THREAD

**Issue by mreiger** [metal-stack/gardener-extension-provider-metal#54]
Steps:

* [ ] Inject command line options of shoot apiservers to turn on dynamic auditlogging
* [ ] Provide audit policy to apiserver
* [ ] Forward the auditlog to a splunk HEC endpoint, passing the right HEC token. Use https://github.com/metal-stack/kubernetes-splunk-audit-webhook.
  * [ ] Find a way to pass the proper hec token to splunk. The token can differ from apiserver to apiserver, e.g. to differentiate between tenants on the splunk side.

**Comment by droid42** [comment]
## Implementation hints

**Audit-Config**

* Template for audit-config analogous to charts/internal/cloud-provider-config/templates/authn-webhook-config.yaml
* Valuesprovider for config, see pkg/controller/controlplane/valuesprovider.go
  * register config chart: pkg/controller/controlplane/valuesprovider.go:160
  * provide values (optional): pkg/controller/controlplane/valuesprovider.go:318

**API-Server-Mutation**
* pkg/webhook/controlplane/ensurer.go:43

**Fluentbit Sidecar Container**
`extensionswebhook.EnsureContainerWithName` 

Idea: use FluentBit-Sidecar using shared volume where audit-log is written
see https://kubernetes.io/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume/

**Comment by droid42** [comment]
We have to read the token for the target splunk from masterdata tenant-annotations and - if it exists - create a Secret for mounting in the FluentBit-Sidecar.

**Comment by mreiger** [comment]
Branch for work on this issue: https://github.com/metal-stack/gardener-extension-provider-metal/tree/fix-54

**Comment by mreiger** [comment]
The original plan got superseded by the implementation of https://github.com/metal-stack/kubernetes-splunk-audit-webhook - Closing this pull request and branch; starting over.

**Comment by mreiger** [comment]
Current state:
* An instance of the [splunk audit webhook](https://github.com/metal-stack/kubernetes-splunk-audit-webhook) gets deployed
* Dynamic auditing is switched on in the apiserver
* Splunk HEC endpoint and token are statically defined (dummy values for now)
* An initial audit policy ist defined:
```
                level: Metadata
                stages:
                - ResponseComplete
```
* A config switch is in place that will enable all the things mentioned above; default: Disabled

Next steps:
* [ ] Enable the configuration and see that auditing is enabled there are attempts to send audit events to the dummy endpoint
* [ ] Implement fields for splunk HEC endpoint and token in the masterdata api: Issue https://github.com/metal-stack/masterdata-api/issues/23
* [ ] Modify the extension provider to pull these fields from the masterdata api
