### ISSUE TITLE
Metal API URL should be part of the `CloudProfile`

### ISSUE THREAD

**Issue by rfranzke** [metal-stack/gardener-extension-provider-metal#63]
Today, the URL to the MetalStack API is part of the `cloudprovider` secret: https://github.com/metal-stack/gardener-extension-provider-metal/blob/master/example/30-infrastructure.yaml#L11.

This requires every user to enter it into its secret although it's always the same for one MetalStack environment.
It'd be more convenient and improve the user experience if the operator could configure it in the `CloudProfile` instead, similar to the [Keystone URL of OpenStack](https://github.com/gardener/gardener-extension-provider-openstack/blob/master/docs/usage-as-operator.md#cloudprofileconfig).

**Comment by Gerrit91** [comment]
Sounds very reasonable. Thanks for opening this issue. I can take care of this when I have time for these things again.

**Comment by majst01** [comment]
fixed in v0.10.0
